### ISSUE TITLE
Optimize LabChangeMatrix

### ISSUE THREAD

**Issue by raikens1** [HealthRex/CDSS#131]
Features to add/debug for LabChangeMatrix:
- [x] Add index to db so LabChangeMatrix runs faster
- [x] Query only rows where last value of lab was measured - added a filter feature to FMTransform.  a little hacky, but good enough for now.

**Comment by SanthoshBala** [comment]
I just tried this again, and the full script to build a 10000 row matrix only took 10 minutes. 

Dug into a few potential performance issues anyway though, and don't think the index is the issue (psql EXPLAIN shows that the query never does a sequential scan). The key bottlenecks are:
(1) The ORDER BY (this is a critical element of how FeatureMatrixFactory works, so would require some broader refactoring to change this)
(2) The pat_id WHERE clause (we do this to ensure that we are collecting all of the orders for a random set of patients, rather than a random set of orders across a random set of patients). I'm not sure whether this is strictly necessary, but seemed better in terms of our ability to reason about the dataset represented by any given feature matrix.
(3) Querying a remote vs local database.

Will keep thinking about ways to improve this though (there may be some redundant queries at the moment).
