### ISSUE TITLE
Add more notes on setup process

### ISSUE THREAD

**Issue by raikens1** [HealthRex/CDSS#137]
Would be great to have a consolidated set of instructions (i.e. on the Wiki) for new lab members to:
- run setup/setup.sh 
- set up local database with Stride data
- get connected to AWS database

Plus: have _brief_ explanations for users new to psql to understand what they're doing when they run the setup scripts

Note: doesn't have to be perfect - some amount of debug time is inevitable from person to person.

**Comment by SanthoshBala** [comment]
@raikens1 @kwosei mind if I take this on? I'm gonna be refactoring the setup process a bit anyway so that everyone gets the 2014-2017 data, so I can update some of our existing Wiki pages (e.g. https://github.com/HealthRex/CDSS/wiki/Dev-Environment-Setup) and make sure that some of the scripts are self-documenting in a better way.

**Comment by kwosei** [comment]
sounds good! @SanthoshBala

**Comment by jonc101** [comment]
setup.sh needs to be disentangled from PostgreSQL database setup.
Precondition should be setup of database (otherwise cannot make consistent guess of where the database is. Tries to setup local configurations, even if using a remote database)

**Comment by jonc101** [comment]
Shared AWS HealthRex-db snapshot should not have a default "jonc101" user. Should be some generic "db-user" or something, with default password specified somewhere.
