### ISSUE TITLE
BigQuery database, convert string dates into proper datetime/timestamp column data type

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#194]
Several of the date columns in our BigQuery copy of the deidentified clinical data is stored as strings. These should be converted to proper datetime/timestamp column data types to facilitate future date queries and calculations.

**Comment by JonathanChiang** [comment]
Big Query Notes: 

https://cloud.google.com/bigquery/docs/manually-changing-schemas

Changing a column's data type

Changing a column's data type is not supported by the GCP Console, the classic BigQuery web UI, the command-line tool, or the API. If you attempt to update a table by applying a schema that specifies a new data type for a column, the following error is returned: BigQuery error in update operation: Provided Schema does not match Table [PROJECT_ID]:[DATASET].[TABLE].

There are two ways to manually change a column's data type:

Using a SQL query — Choose this option if you are more concerned about simplicity and ease of use, and you are less concerned about costs.
Recreating the table — Choose this option if you are more concerned about costs, and you are less concerned about simplicity and ease of use.
Option 1: Using a query
Use a SQL query to select all the table data and to cast the relevant column as a different data type. You can use the query results to overwrite the table or to create a new destination table.

Pros
Using a query to write the data to a new destination table preserves your original data.
If you use the query job to overwrite the original table, you incur storage costs for one table instead of two, but you lose the original data.
Cons
Changing a column's data type using a query requires you to scan the entire table — The query charges can be significant if the table is very large.
If you write the query results to a new destination table, you incur storage costs for both the old table and the new one (unless you delete the old one).
Option 2: Exporting your data and loading it into a new table
You can also change a column's data type by exporting your table data to Cloud Storage, and then loading the data into a new table with a schema definition that specifies the correct data type for the column. You can also use the load job to overwrite the existing table.

Pros
You are not charged for the export job or the load job. Currently, BigQuery load and export jobs are free.
If you use the load job to overwrite the original table, you incur storage costs for one table instead of two, but you lose the original data.

**Comment by jonc101** [comment]
Sounds like worth figuring out the second option. Downloading then reuploading the dataset. Will be useful experience as well (sounds like you figured out some already) to facilitate future data table loads.

Jonathan

**Comment by JonathanChiang** [comment]
Should we migrate to Nero and let the Nero team update the schema or would you like me to rue-load the data with updated schema on GCP ?

**Comment by jonc101** [comment]
If they’ll do it for “free,” probably better to let them do some work for us, so you can focus on other items.

**Comment by JonathanChiang** [comment]
https://bigquery.cloud.google.com/table/mining-clinical-decisions:clinical_inpatient.reupload_encounter_sample?pli=1&tab=preview

I reuploaded the sample encounter table successfully with datetime. Making sure I understand how to upload a table with new schema from bq. I will follow up with the Nero team about migrating

**Comment by JonathanChiang** [comment]
Completed see starr-datalake2018
