### ISSUE TITLE
Sanity checking for simple association study 

### ISSUE THREAD

**Issue by sxu11** [HealthRex/CDSS#220]
[] how to fill in the “specialty” field for many departments?
[] what is the exact DIC SCREEN cnt in 2016 outpatient data?
[] handle the case where 1 specialty encounter maps to >1 referral encounters?
[] handle the case where 1 referral encounter maps to >1 ICD10 codes?
[] Does “New Patient Visit” ensures outpatient setting?
[] Relative Risk w.r.t. only Primary Care, instead of w.r.t. any department visits?
[] Make sure “cancelled” encounters/orders are not included

**Comment by sxu11** [comment]
Seems like most depts that miss a 'specialty name' do not get visited anyway. (only 8 out of 55858 visits are to these depts). So probably don't have to worry for now.

**Comment by JonathanChiang** [comment]
- Will try to get bandwidth for next week to work on this explicitly. 

- For Discussion Purposes, can you answer this? 
- [ ] how to fill in the “specialty” field for many departments?
    - I'm assuming this would be manual and we would need a co-collaborator to explicitly label these. We can make really educated guesses based on string matching and department names, but once we develop a POC we should confirm with specialists about our methods. This would require much more additional overhead. so we should be patient about that aspect and potentially mention in the **grant** that this would need to be a fixed expense for collaboration. 
- [ ] what is the exact DIC SCREEN cnt in 2016 outpatient data?
   - jon chen recently made a google big query dev workshop. should reference to complete this. this task is straight forward and can be done 
- [ ] handle the case where 1 specialty encounter maps to >1 referral encounters?
    - may require changing methodology, your methodology currently looks at 6 month and new visit mapping from referral. Would need to generalize this process based on more explicit parameters, to reduce noise among mappings 
- [ ] handle the case where 1 referral encounter maps to >1 ICD10 codes?
     - icd10 codes are notoriously ambiguous/unreliable (based on literature and Jon Chen), but may suggest clues for association as you've done 
- [ ] Does “New Patient Visit” ensures outpatient setting?
     - would require looking at outpatient and inpatient flag in big query (look into sql schema) 

- [ ] Relative Risk w.r.t. only Primary Care, instead of w.r.t. any department visits?
  -  unclear about this one, may need more details 

- [ ] Make sure “cancelled” encounters/orders are not included
    -  could you provide an example of cancelled encounter?? is there a flag for orders that are filled? potentially order_time_jittered and a delivery_time_jittered or administered_time_jittered to confirm that order occured. again, i feel more explicit mapping would be required. 




- side note: I updated the schema of the entire bq outpatient-inpatient data to adjust for datetime in a new table: so may need to update your script to configure for this.

**Comment by sxu11** [comment]
- "how to fill in the “specialty” field for many departments?"
As mentioned in my previous comment, this is no longer an issue because departments without a "specialty" field happen to be the ones that got extremely rarely visited.
