### ISSUE TITLE
Access Log Data (ct head)

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#245]
Retrieve and sync Access Log info for ER CT Head cases

Susan Weber said will take a while in May 2019, as in middle of some system upgrades...

6/20/2019 - Reminder ping to Susan Weber asking for status

10/2019 - Tina Seto has data, deidentifying. Waiting for Nero BigQuery instance for delivery?

**Comment by JonathanChiang** [comment]
- [ ] Prepare a cox-regression model for clinical events

**Comment by JonathanChiang** [comment]
- [ ] TO DO 
- [ ] GET ASSOCIATIONS FOR TPA ORDER 
- [ ]  GET ASSOCIATIONS FOR CT HEAD UNDER 10 and Then Greater than 50 
- [ ]  Construct Cox Regression for TPA order as Diagnostic Procedure

**Comment by JonathanChiang** [comment]
Meeting Notes: Christian: 

-- tpa order decision-making: 
-- ER doctors: tpa versus doing nothing (versus neurology) 
-- tpa (decision-making ED versus Neurology) 
-- looking at provider percentage: above (confidence to order) neurology limited availability 
-- Kaiser: solutions: teleradiology (video: look at neurology) NIHSS stroke scale: 
-- rule-based exam (automate with query??) 
-- ring-down (ambulance call) 
-- greater than 4-6 hour (no tpa) 
-- timing (sleep) (unclear when last normal due to sleep) 
-- within 12 hours (IR guided clot retrieval?) 
-- order ct (non-contrast bleed or no bleed) (if no bleed = ct with contrast) (with blood clot -> tpa or IR)
-- stroke (neurology may come over) 
-- ED doctor (neurology versus ed doctor making the decision may be different at different hospitals) (rural versus academic) 
-- deferring to expertise: or encoding expertise locally (knowledge-based system, order set??)

**Comment by JonathanChiang** [comment]
- actionable items with christian: 
- Provider Specialty: (ER Doc versus Specialist) 
- Number of Patients in that Hour
