### ISSUE TITLE
Cleanup STARR DataLake on BigQuery time fields as PST vs. UTC time zone

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#286]
Datalake previously provided by Susan Weber (datalake_47618) stored datetime fields as strings.
These were all converted to TIMESTAMP fields in starr_datalake2018, but default assumption was that string datetime's represented UTC times. This appears to be incorrect however, as they actually represented local Pacific time, as confirmed by TIna Seto.

Either all the timestamp values in starr_datalake2018 need to be revised, or they need to be reloaded from the source datalake with a proper timezone conversion to UTC / timestamp Unix epoch time long integers.

Please also update the group Wiki pages on using BigQuery / SQL databases with this timezone gotcha, and how to do timezone conversions on the fly for viewing specific data as suggested below.

Consider DATETIME field instead to include specific timezone information, or stick to TIMESTAMPs for unambiguous time representation that only changes with respect to view/query

E.g., 
select order_time_jittered, STRING(order_time_jittered,"America/Los_Angeles") as pstime
from starr_datalake2018.order_med
limit 100

select *
from datalake_47618.order_med
where order_med_id_coded = 499835472
limit 100

11:43 AM
2016-06-14 16:48:00
2016-06-14 00:00:00
2016-07-04 00:00:00
11:43 AM
order_time_jittered, start_time, end_time
11:43 AM
Above was the raw string date in data lake. We converted these into timestamp objects, based on assumption they were UTC time, but maybe they were actually Pacific?

=======================

datetime fields made them UTC timestamps, and add a copy column "local_datetimefield" to represent local datetime of capture.

Consider swapping/renaming these to the source datetime field representation, and a respective "utc_datetimefield" timestamp, to better match the source data

**Comment by ynodir** [comment]
After some discussions the decision was made to:
1) create a `local_*` field per each converted `TIMESTAMP` field to represent the PT as is without the timezone information;
2) convert `TIMESTAMP` fields to PT - will be displayed in UTC time in bigquery UI.

**Comment by ynodir** [comment]
Conversion progress:
1. `drg_code` 2 rows - no timestamps = no conversion
2. `dep_map` 4k rows - no timestamps = no conversion
3. `ndc` 140k rows - no timestamps = no conversion
4. `ndc_code` 140k rows - no timestamps = no conversion
5. `prov_map` 165k rows - no timestamps = no conversion
6. `drg` 650k rows - no timestamps = no conversion
7. `culture_sensitivity` 830k rows - converted
8. `allergy` 890k rows - `timestamp` fields have only `00:00:00` times = no conversion
9. `path_report_meta` 1.2m rows = converted only `result_time_jittering` (most of `ordering_time_jittering` time is 00:00:00 ~1.2m, `proc_end_time_jittering` is always null, ~20% of `proc_start_time_jittering` is also 00:00:00)
10. `demographic` 2.2m rows (all birth_date_jittered times are 00:00:00, more than 99% of non-null death_date_jittered values are 00:00:00 (122921), all non-null recent_conf_enc_jittereds are 00:00:00)
11. `radiology_report_meta` 6m rows (all `ordering_date_jittered` times are 00:00:00)
12. `social_hx` 7.5m rows (both `contact_date_jittered` and `smokeless_quit_date_jittered` are dates, i.e. times are 00:00:00)
13. `treatment_team` 8.3m rows
14. `med_orderset` 9.1m rows - no timestamps = no conversion
15. `family_hx` 17m rows (`contact_date_jittered` timestamp has only 00:00:00 times)
16. `adt` 19m rows (about 1/3 of effective_time_jittered is 23:59:00)
17. `proc_orderset` 24m rows - no timestamps = no conversion
18. `order_med` 53m rows (~10% of order_time_jittered have 00:00:00, ~1/3 of start_time_jittered have 00:00:00, ~20% of end_time_jittered have 00:00:00 and other ~5% - 23:59:00)
19. `clinical_doc_meta` 60m rows (~5% of filing_date_jittered is either 00:00:00 or 00:01:00, ~5% of note_date_jittered is 00:00:00, ~5% of activity_date_jittered is 00:00:00, ~75% of effective_time_jittered is 00:00:00)
20. `procedure_code` 69m rows (not converting: ~99% of start_date_jittered is 00:00:00, all of proc_date_jittered is 00:00:00, ~95% of adm_date_time_jittered is 00:00:00)
21. `mar` 71m rows (need a unique key to check the timestamp conversion - currently, timestamps seem to be a part of unique key)
22. `diagnosis_code` 95m rows (doesn't seem to have a unique key? >50% of timestamp has 00:00:00, all of noted_date_jittered have 00:00:00, all of hx_date_of_entry_jittered have 00:00:00, all of resolved_date_jittered have 00:00:00, end_date_jittered has 100x more of 00:00:00 than other times - most values are null)
23. `encounter` 102m rows (all of contact_date_jittered is 00:00:00, 2/3 of appt_when_jittered is 00:00:00, ~60% of non-null hosp_dischrg_time_jittered is 00:00:00 or 23:59:00)

24. `order_proc` 225m rows (ordering_date_jittered - only 00:00:00, standing_exp_date_jittered - only 00:00:00, ~10% of order_time_jittered is 00:00:00, >10% of non-null result_time_jittered is 00:00:00, ~25% of proc_start_time_jittered is 00:00:00, all of proc_date_jittered is 00:00:00, all of last_stand_perf_dt_jittered is 00:00:00, last_stand_perf_tm_jittered is a subset of last_stand_perf_dt_jittered, otherwise datewise they're the same - last_stand_perf_dt_jittered can be dropped after the values are copied to last_stand_perf_tm_jittered where it is NULL)
25. `lab_result` 312m rows (result_time_jittered - 9m 00:00:00s then comes 12:14:00 with 0.5m records) - converted
26. flowsheet 2.4b rows - converted

**Comment by ynodir** [comment]
Examples of queries run during conversion:

1) Timezone conversion SQL Update for `culture_sensitivity` table:
`update starr_datalake2018.culture_sensitivity
set local_order_time_jittered = case order_time_jittered when null then null else datetime(timestamp(datetime(order_time_jittered), 'America/Los_Angeles'), 'America/Los_Angeles') end,
    order_time_jittered = case order_time_jittered when null then null else timestamp(datetime(order_time_jittered), 'America/Los_Angeles') end,
    local_result_time_jittered = case result_time_jittered when null then null else datetime(timestamp(datetime(result_time_jittered), 'America/Los_Angeles'), 'America/Los_Angeles') end,
    result_time_jittered = case result_time_jittered when null then null else timestamp(datetime(result_time_jittered), 'America/Los_Angeles') end,
    local_sens_obs_inst_tm_jittered = case sens_obs_inst_tm_jittered when null then null else datetime(timestamp(datetime(sens_obs_inst_tm_jittered), 'America/Los_Angeles'), 'America/Los_Angeles') end,
    sens_obs_inst_tm_jittered = case sens_obs_inst_tm_jittered when null then null else timestamp(datetime(sens_obs_inst_tm_jittered), 'America/Los_Angeles') end,
    local_sens_anl_inst_tm_jittered = case sens_anl_inst_tm_jittered when null then null else datetime(timestamp(datetime(sens_anl_inst_tm_jittered), 'America/Los_Angeles'), 'America/Los_Angeles') end,
    sens_anl_inst_tm_jittered = case sens_anl_inst_tm_jittered when null then null else timestamp(datetime(sens_anl_inst_tm_jittered), 'America/Los_Angeles') end
where true;
`

**Comment by ynodir** [comment]
Attached UPDATE queries used for conversion along with the conversion check queries.

[scratch.zip](https://github.com/HealthRex/CDSS/files/3738934/scratch.zip)

**Comment by ynodir** [comment]
Conversion is done together with renaming fields to `_utc` timestamp and original name.
Closing the issue.
