### ISSUE TITLE
Migrate CDSS to python3

### ISSUE THREAD

**Issue by SanthoshBala** [HealthRex/CDSS#29]
This isn't urgent, but we know we'll need to do it eventually and it'll be painful =)

**Comment by jonc101** [comment]
http://python3statement.org/
Looks like 2020 is planned to be the hard change date.
I'm mostly stalling for now while Amazon EC2 instances still default Python is 2.7. Once they make the jump, then I'll know it is time.
There are code conversion tools to help automate some of the transition.

**Comment by ynodir** [comment]
https://portingguide.readthedocs.io/en/latest/process.html

Python 3 conversion steps:
1. 2to3 tool (overwrites in-place):
   python c:\python38\Tools\scripts\2to3.py -n -W .
2. install required libs
2.a. google-cloud-bigquery
2.b. pandas-util
2.c. scipy
2.d. gensim
2.e. mock
2.f. matplotlib
2.g. openeye?
2.h. psycopg2
2.i. google-api-core
2.j. google-api-python-client
2.k. google-api-python-client-py3
2.l.
...
3. UserDict is gone - replace with collections.UserDict
4. Remove old .pyc binaries:
   find . -name "*.pyc" -exec rm {} +

5. Run TestDBUtil.py
6.a. Needed to replace "chunk.encode('string_escape')" with "chunk.encode('unicode_escape').decode('utf-8')"

7. Python 3 '/' operator returns float instead of int - need to use '//'
8. gensim library doesn't work on Python 3.8 - time.clock() is deprecated in Windows 10, apptly
9. max([0, None]) works in Python 2.7 whereas it throws TypeError in Python 3.6
10. newly, in gzip.open() - 'w' is interpreted as binary; 'wt' for text mode
11. test_ivFluids error - dicts aren't comparable anymore, so heappush(infusionEndItemHeap, (ivFluidItem["end_taking_time"], infusionEndItem)) throws exceptions
12. repeat_component_descriptive.py - replaced "dtype='string'" to [df_global_stats, pd.DataFrame(to_df, dtype='object').fillna('NULL')])
13. floats seem more precise: '38167.84722222222' vs '38167.8472222' - might need to modify expected values in tests or pre-calculate them
14. TestBatchTTests.py - sorting issues? None is coming on top instead of being at the end? - for now modified the order of expected values
15. Although, __init__.py files aren't necessary anymore - they're required for `TestCDSS.py` as otherwise it can't find the tests - this is an old issue which hadn't been solved yet in `unittest`

**Comment by ynodir** [comment]
NOTE: `TestCDSS` tests should run in VPN as STARR conversion tests require it to connect to bigquery.

**Comment by ynodir** [comment]
Current state of `TestCDSS` (need to look into STARR conversion tests - failing randomly):

======================================================================
ERROR: test_topicModelAnalysis (medinfo.cpoe.analysis.test.TestTopicModelAnalysis.TestTopicModelAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\CDSS\medinfo\cpoe\analysis\test\TestTopicModelAnalysis.py", line 209, in test_topicModelAnalysis
    self.analyzer.main(argv);
  File "\CDSS\medinfo\cpoe\analysis\TopicModelAnalysis.py", line 171, in main
    formatter.formatResultDicts( analysisResults, colNames );
  File "\CDSS\medinfo\db\ResultsFormatter.py", line 60, in formatResultDicts
    for self.currRow, rowDict in enumerate(resultDicts):
  File "\CDSS\medinfo\cpoe\analysis\TopicModelAnalysis.py", line 63, in __call__
    preparer
  File "\CDSS\medinfo\cpoe\analysis\TopicModelAnalysis.py", line 93, in analyzePatientItems
    recommendedData = recommender( recQuery );
  File "\CDSS\medinfo\cpoe\TopicModelRecommender.py", line 95, in __call__
    weightByItemId = self.weightByItemIdByTopicId[topicId];
KeyError: 59

======================================================================
FAIL: test_data_conversion_7_with_normalizeMixtures_DoseCountLimit_excludeRoute (medinfo.dataconversion.starr_conv.test.TestSTARROrderMedConversion.TestSTARROrderMedConversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\AppData\Roaming\Python\Python36\site-packages\parameterized\parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "\CDSS\medinfo\dataconversion\starr_conv\test\TestSTARROrderMedConversion.py", line 1561, in test_data_conversion
    self.assertEqualTable(self.expected_orderset_data, actual_orderset_data)
  File "\CDSS\medinfo\common\test\Util.py", line 175, in assertEqualTable
    self.assertEqual(len(verifyTable), len(sampleTable))
AssertionError: 2400 != 2394

======================================================================
FAIL: test_build_FeatureMatrix_multiLabTest (medinfo.dataconversion.test.TestFeatureMatrixFactory.TestFeatureMatrixFactory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\CDSS\medinfo\dataconversion\test\TestFeatureMatrixFactory.py", line 342, in test_build_FeatureMatrix_multiLabTest
    self.assertEqualTable(expectedMatrix, resultMatrix[2:], precision=5)
  File "\CDSS\medinfo\common\test\Util.py", line 184, in assertEqualTable
    self.assertEqualGeneral(verifyItem, sampleItem, precision);
  File "\CDSS\medinfo\common\test\Util.py", line 99, in assertEqualGeneral
    return self.assertEqual( verifyValue, sampleValue );
AssertionError: 3 != 0

----------------------------------------------------------------------
Ran 154 tests in 1727.337s

FAILED (failures=2, errors=1)

**Comment by ynodir** [comment]
Using Python 3.6 as Python 3.8 isn't supported by gensim library yet.

**Comment by jonc101** [comment]
- [ ] Can you also update the setup/webAppSetupNotes.txt to reflect the Python 3.6 + Apache 2.4 configuration? Is 90% similar, but a couple variations in command directives.
