### ISSUE TITLE
Add DevWorkshop ReadMe on creating and using a GCP compute server to interact with database, use the AWS example as a template

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#315]

**Comment by JonathanChiang** [comment]
[reference for dev workshop](https://github.com/HealthRex/CDSS/blob/master/scripts/DevWorkshop/ReadMe.AWSDevEnvironment.txt)

**Comment by JonathanChiang** [comment]
1  sudo apt update
    2  sudo apt install python3 python3-dev python3-venv
    3  wget https://bootstrap.pypa.io/get-pip.py
    4  sudo python get-pip.py
    5  mkdir  bg_project
    6  cd bg_project/
    7  python3 -m venv venv
    8  source venv/bin/activate
    9  pip install google-cloud-storage
   10  pip install google-cloud-bigquery
   11  pip install pandas

**Comment by JonathanChiang** [comment]
`
from google.cloud import bigquery
client = bigquery.Client(project='mining-clinical-decisions')

project_id = 'mining-clinical-decisions'

sql = '''
      SELECT
        jc_uid, order_type,  description
      FROM
        `datalake_47618_sample.order_proc`
      Order By
         ordering_date_jittered DESC
    '''

# Run a Standard SQL query using the environment's default project
df = client.query(sql).to_dataframe()

df = client.query(sql, project=project_id).to_dataframe()
print(df)`

**Comment by JonathanChiang** [comment]
[ssh](https://cloud.google.com/compute/docs/instances/connecting-advanced)

**Comment by JonathanChiang** [comment]
http://www.e2college.com/blogs/risk_management/security_design_principles.html

**Comment by JonathanChiang** [comment]
sudo  apt install  git 

[ ] How to make compute instance private? 
            - IAM  process 

[ ] https://cloud.google.com/compute/docs/oslogin/

[X]         ???????????Vs. Having users upload login JSON key to identify themselves???????
                - Tested: causes major security flaws: other users in default can access others folders 
                - export GOOGLE_APPLICATION_CREDENTIALS='/home/jichiang/Mining Clinical Decisions-credential.json' 
                - realizes that this causes others to have access to individual keys
                - uploading JSON credentials  to vm instances  expose the  credential to other  users  

[X]         ???????Especially because som-nero-phi-jonc101 project, we don't have owner access to create API accounts anyway....
                - Reached out to Nero Team to  see  what best practice is (GCP recommends IAM control)

[X]         ????? Would probably then be good for people to know about SCP file uploads as well?????
                - can use gcloud init  to  upload  files 
                - gcloud compute scp ~/Downloads/gcp-AWS.txt \compute-engine-default-access-test:~/test_scp

[X]         ???? This probably means as a precondition, that they've already done the GoogleCloud-VPC Access Key workshop so they'll have they're own JSON ????
                -  uses gcloud init  

[X]         [[[[[ Figure out what is minimum necessary dependency installation to just make demo process work]]]]]
[X]         [[[[[ See if simpler git install so doesn't require so much download and install ]]]]]
                - removed git-all 

[X]         [[[[[[[[[[[[ Add back example where the compute/query process takes a while, adding back option parser and time delay between results]]]]]]]]]]]]
            [[[[[[[[[[[[ That way people can learn about running a process in the background...]]]]]]]]]]]
                - sleeper.py file 

[X]         no service api makes it so it doesn't work  



https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#createsshkeys

[X] check project history to see whether  queries are audited?
    - requires permission PROJECT OWNER  
    - To give users the ability to create and manage your Compute Engine resources, 
    - you can add users as team members to your project or to specific resources and grant them permissions using Cloud Identity and Access Management roles.

[ ] https://cloud.google.com/compute/docs/instances/access-overview


 gcloud compute scp ~/downloads/gcp-AWS.txt \compute-engine-default-access-test:~/jichiang 

 https://cloud.google.com/compute/docs/instances/connecting-to-instance

**Comment by JonathanChiang** [comment]
Hi Jonathan,

Nero GCP is restricted to SRCC being able to bring up compute engine resources along with the creation of service accounts due to the high risk data approved nature of the project. If you would like a service account created, we are happy to help create one but would appreciate an understanding of the reason for it. 

We can give permissions for you/others to create Buckets, and BigQuery actions within the Nero GCP project.

Best,
Neal
