### ISSUE TITLE
STARR (SHC + LPCH) Datalake Update 2022

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#390]
Requested to Yelena before Dec 2022 break.

**Comment by jonc101** [comment]
[ ] Update naming to shc_core_2022 (to reflect that it has all 2022 data. Any 2023 is only a little bonus, but not complete)
[ ] Check that treatment_team_code is not necessariy/redundant
[ ] Replace flowsheet with flowsheet_with_meas content, if they are now equivalent
[ ] Follow-up Yelena on lpch_core_2022 equivalent 
and shc_access_log data
[ ] Notify everybody (@general) channel that data update is there, and they should look through it to see if it includes what they need, or if we need to ask for any other updates.
[ ] Ask Yelena for the mapping table (MRN to anon ID) also need the date jitter for each, so we can reconstruct real times.
   [ ] Ask Yelena if it's also possible to get a mapping table for pat_enc_csn_id (encounter IDs)
   [ ] Move that mapping table under starr_map and call in shc_map_2022

**Comment by sajjadfouladvand** [comment]
[] Update naming to shc_core_2022 (to reflect that it has all 2022 data. Any 2023 is only a little bonus, but not complete)
      - Done
[ ] Check that treatment_team_code is not necessariy/redundant
      - It was the same. In the new shc_core_2022 we only have treatment_team. 
[ ] Replace flowsheet with flowsheet_with_meas content, if they are now equivalent
      - Done.
[ ] Notify everybody (@general) channel that data update is there, and they should look through it to see if it includes what they need, or if we need to ask for any other updates.
      - Done
[ ] Follow-up Yelena
[ ] lpch_core_2022 equivalent
[ ] shc_access_log data (update with an shc_access_log_2022... or maybe just update the prior one, since it's such a large file >3TB, replace / update the prior version)
[ ] Ask Yelena for the mapping table (MRN to anon ID) also need the date jitter for each, so we can reconstruct real times.
[ ] Ask Yelena if it's also possible to get a mapping table for pat_enc_csn_id (encounter IDs)
      - Done
[ ] Move that mapping table under starr_map and call in shc_map_2022
      - Done
